# Generated by Django 6.0.3 on 2026-03-26 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_author_alter_post_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="author",
            new_name="following",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "following")},
        ),
    ]
